-- neighborhood
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(102,'Vista Hermosa','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(196,'Sector Patio Bonito','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(199,'Aguacatal','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(201,'Santa Rita','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(202,'Santa Teresita','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(203,'Arboledas','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(206,'Centenario','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(207,'Granada','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(208,'Versalles','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(209,'San Vicente','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(211,'Prados del Norte','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(212,'La Flora','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(214,'La Paz','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(215,'El Bosque','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(216,'Menga','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(217,'Ciudad Los Alamos','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(218,'Chipichape','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(219,'Brisas de los Alamos','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(293,'Urbanización La Merced','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(294,'Vipasa','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(296,'Altos de Menga','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(298,'Area en desarrollo - Parque del Amor','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(301,'El Nacional','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(303,'San Antonio','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(304,'San Cayetano','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(305,'Los Libertadores','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(306,'San Juan Bosco','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(307,'Santa Rosa','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(308,'La Merced','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(309,'San Pascual','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(310,'El Calvario','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(311,'San Pedro','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(312,'San Nicolas','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(313,'El Hoyo','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(314,'El Piloto','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(315,'Navarro - La Chanca','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(401,'Jorge Isaacs','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(402,'Santander','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(403,'Porvenir','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(404,'Las Delicias','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(405,'Manzanares','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(406,'Salomia','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(410,'Popular','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(411,'Ignacio Rengifo','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(412,'Guillermo Valencia','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(413,'La Isla','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(416,'La Esmeralda','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(417,'Bolivariano','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(418,'Olaya Herrera','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(419,'Unidad Residencial Bueno Madrid','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(420,'Flora Industrial','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(421,'Calima','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(423,'Industria de Licores','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(497,'La Alianza','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(501,'El Sena','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(502,'Los Andes','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(503,'Los Guayacanes','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(504,'Chiminangos Segunda Etapa','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(505,'Chiminangos Primera Etapa','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(506,'Metropolitano del Norte','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(594,'Los Parques - Barranquilla','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(595,'Villa del Sol','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(596,'Paseo de Los Almendros','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(597,'Los Andes B - La Riviera','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(598,'Torres de Comfandi','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(599,'Villa del Prado - El Guabito','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(603,'Paso del Comercio','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(605,'Petecuy Primera Etapa','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(606,'Petecuy Segunda Etapa','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(607,'La Rivera Primera Etapa','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(608,'Los Guaduales','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(609,'Petecuy Tercera Etapa','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(610,'Ciudadela Floralia','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(695,'Fonaviemcali','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(696,'San Luís II','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(697,'Urbanización Calimio','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(698,'Sector Puente del Comercio','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(701,'Alfonso López P. 1a. Etapa','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(702,'Alfonso López P. 2a. Etapa','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(703,'Alfonso López P. 3a. Etapa','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(704,'Puerto Nuevo','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(705,'Puerto Mallarino','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(706,'Urbanización El Angel del Hogar','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(707,'Siete de Agosto','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(708,'Los Pinos','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(709,'San Marino','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(710,'Las Ceibas','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(711,'Base Aérea','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(797,'Parque de la Caña','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(798,'Fepicol','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(801,'Primitivo Crespo','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(802,'Simón Bolívar','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(803,'Saavedra Galindo','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(804,'Uribe Uribe','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(805,'Santa Mónica Popular','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(806,'La Floresta','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(807,'Benjamín Herrera','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(808,'Municipal','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(809,'Industrial','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(810,'El Troncal','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(811,'Las Américas','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(812,'Atanasio Girardot','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(813,'Santa Fe','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(814,'Chapinero','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(815,'Villa Colombia','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(816,'EL Trébol','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(817,'La Base','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(818,'Urbanización La Nueva Base','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(901,'Alameda','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(902,'Bretaña','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(903,'Junn','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(904,'Guayaquil','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(905,'Aranjuez','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(906,'Manuel María Buenaventura','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(907,'Santa Mónica Belalcázar','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(908,'Belalcázar','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(909,'Sucre','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(910,'Barrio Obrero','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1001,'El Dorado','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1002,'El Guabal','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1003,'La Libertad','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1004,'Santa Elena','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1005,'Las Acacias','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1006,'Santo Domingo','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1007,'Jorge Zawadsky','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1008,'Olímpico','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1009,'Cristóbal Colón','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1010,'La Selva','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1011,'Barrio Departamental','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1012,'Pasoancho','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1013,'Panamericano','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1014,'Colseguros Andes','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(101,'Terrón Colorado','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(204,'Normandía','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(205,'Juanambú','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(210,'Santa Mónica ','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(213,'La Campiña','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(295,'Urbanización La Flora','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(302,'El Peñón','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(407,'Fátima','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(408,'Sultana - Berlín - San Francisco ','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(414,'Marco Fidel Suárez','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(415,'Evaristo García','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(601,'San Luis','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(602,'Jorge Eliecer Gaitán','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(604,'Los Alcázares','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1015,'San Cristobal','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1016,'Las Granjas','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1017,'San Judas Tadeo I Etapa','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1018,'San Judas Tadeo II Etapa','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1101,'San Carlos','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1102,'Maracaibo','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1103,'La Independencia','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1104,'La Esperanza','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1105,'Urbanización Boyacá','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1106,'El Jardín','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1107,'La Fortaleza','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1108,'El Recuerdo','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1109,'Aguablanca','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1110,'El Prado','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1111,'20 de Julio','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1112,'Prados de Oriente','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1113,'Los Sauces','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1114,'Villa del Sur','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1115,'José Holguín Garcés','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1116,'León XIII','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1117,'José María Cordoba','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1118,'San Pedro Claver','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1119,'Los Conquistadores','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1120,'La Gran Colombia','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1121,'San Benito','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1122,'Primavera','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1201,'Villanueva','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1202,'Asturias','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1203,'Eduardo Santos','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1204,'Alfonso Barberena A.','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1205,'El Paraiso','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1206,'Fenalco Kennedy','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1207,'Nueva Floresta','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1208,'Julio Rincón','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1209,'Doce de Octubre','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1210,'El Rodeo','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1211,'Sindical','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1212,'Bello Horizonte','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1301,'Ulpiano Lloreda','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1302,'El Vergel','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1303,'El Poblado I','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1304,'El Poblado II','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1305,'Los Comuneros Segunda Etapa','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1306,'Ricardo Balcázar','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1307,'Omar Torrijos','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1308,'El Diamante','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1309,'Lleras Restrepo','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1310,'Villa del Lago','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1311,'Los Robles','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1312,'Rodrigo Lara Bonilla','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1313,'Charco Azul','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1314,'Villablanca','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1315,'Calipso','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1390,'Yira Castro','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1393,'Lleras Restrepo II Etapa','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1394,'Marroquín III','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1395,'Los Lagos','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1397,'Sector Laguna del Pondaje','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1398,'El Pondaje','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1399,'Sector Asprosocial-Diamante','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1401,'Alfonso Bonilla Aragón','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1402,'Alirio Mora Beltrán','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1403,'Manuela Beltrán','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1404,'Las Orquídeas','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1405,'José Manuel Marroquín Segunda Etapa','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1406,'José Manuel Marroquín Primera Etapa','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1495,'Puerta del Sol','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1496,'Los Naranjos I','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1498,'Promociones Populares B','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1499,'Los Naranjos II','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1501,'El Retiro','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1502,'Comuneros I','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1503,'Laureano Gómez','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1504,'El Vallado','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1596,'Ciudad Cordoba','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1598,'Mojica','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1599,'El Morichal','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1601,'Mariano Ramos','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1602,'República de Israel','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1603,'Unión de Vivienda Popular','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1604,'Antonio Nariño','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1605,'Brisas del Limonar','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1696,'Área desocupada','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1697,'Ciudad 2000','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1698,'La Alborada','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1701,'La Playa','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1702,'Primero de Mayo','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1703,'Ciudadela Comfandi','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1705,'Ciudad Universitaria','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1774,'Caney','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1775,'Lili','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1778,'Santa Anita - La Selva','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1780,'El Ingenio','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1781,'Mayapan - Las Vegas','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1782,'Las Quintas de Don Simón','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1783,'Ciudad Capri','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1784,'La Hacienda','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1785,'Los Portales - Nuevo Rey','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1786,'Cañaverales - Los Samanes','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1787,'El Limonar','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1788,'Bosques del Limonar','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1789,'El Gran Limonar - Cataya','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1790,'El Gran Limonar','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1791,'Unicentro Cali','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1793,'Ciudadela Pasoancho','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1794,'Prados del Limonar','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1796,'Urbanización San Joaquin','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1801,'Buenos Aires','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1802,'Barrio Caldas','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1803,'Los Chorros','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1804,'Meléndez','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1805,'Los Farallones','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1807,'Francisco Eladio Ramirez','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1808,'Prados del Sur','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1809,'Horizontes','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1810,'Mario Correa Rengifo','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1811,'Lourdes','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1812,'Colinas del Sur','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1813,'Alférez Real','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1814,'Nápoles','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1815,'El Jordán','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1816,'Cuarteles Napoles','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1890,'Sector Alto de Los Chorros','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1891,'Polvorines','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1896,'Sector Meléndez','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1897,'Sector Alto Jordán','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1898,'Alto Nápoles ','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1901,'El Refugio','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1902,'La Cascada','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1903,'El Lido','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1904,'Urbanización Tequendama','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1905,'Barrio Eucarístico','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1906,'San Fernando Nuevo','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1907,'Urbanización Nueva Granada','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1908,'Santa Isabel','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1909,'Bellavista','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1910,'San Fernando Viejo','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1911,'Miraflores','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1912,'3 de Julio','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1913,'El Cedro','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1914,'Champagnat','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1915,'Urbanización Colseguros','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1916,'Los Cambulos','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1917,'El Mortizal','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1918,'Urbanización Militar','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1919,'Cuarto de Legua - Guadalupe','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1921,'Nueva Tequendama ','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1922,'Camino Real - Joaquín Borrero Sinisterra','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1923,'Camino Real - Los Fundadores','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1981,'Altos de Santa Isabel -  La Morelia','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1982,'Santa Barbara','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1983,'Tejares - Cristales','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1984,'Unidad Residencial Santiago de Cali','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1985,'Unidad Residencial El Coliseo','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1988,'Cañaveralejo - Seguros Patria','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1992,'Cañaveral','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1994,'Pampa Linda','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1995,'Sector Cañaveralejo Guadalupe','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1999,'U.D. Alberto Galindo -  Plaza de Toros','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(2001,'El Cortijo','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(2002,'Belisario Caicedo','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(2003,'Siloé','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(2004,'Lleras Camargo','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(2005,'Belén','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(2006,'Brisas de Mayo','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(2007,'Tierra Blanca','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(2008,'Pueblo Joven','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(2097,'Carabineros','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(2098,'Venezuela - Urbanización Cañaveralejo','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(2099,'La Sultana','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(2101,'Pízamos I','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(2102,'Pízamos II','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(2103,'Calimio Desepaz','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(2104,'El Remanso','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(2105,'Los Líderes','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(2106,'Desepaz Invicali','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(2107,'Compartir','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(2108,'Ciudad Talanga','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(2194,'Villamercedes I - Villa Luz - Las Garzas','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(2195,'Pízamos III - Las Dalias','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(2196,'Potrero Grande','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(2197,'Ciudadela del Río','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(2198,'Valle Grande','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(2199,'Planta de Tratamiento','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(2201,'Urbanización Ciudad Jardín','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(2296,'Parcelaciones Pance','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(2297,'Urbanización Río Lili','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(2298,'Ciudad Campestre','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(2299,'Club Campestre','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(297,'Sector Altos De Normandía - Bataclan','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(316,'Acueducto San Antonio','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(1997,'Sector Bosque Municipal','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(6404,'Aguacatal (Vereda Montebello)','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(5905,'El Diamante (Vereda Felidia)','76001');
INSERT INTO opx.neighborhood(neighb_id, neighb_name, city_id) VALUES(6002,'San Antonio (Vereda El Saladito)','76001');
